/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppMarketplaceRouteImport } from './routes/_app.marketplace'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCirclesRouteImport } from './routes/_app.circles'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppAiRouteImport } from './routes/_app.ai'
import { Route as AppProfileUserIdRouteImport } from './routes/_app.profile.$userId'
import { Route as AppCirclesIdRouteImport } from './routes/_app.circles.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCirclesRoute = AppCirclesRouteImport.update({
  id: '/circles',
  path: '/circles',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileUserIdRoute = AppProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppCirclesIdRoute = AppCirclesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCirclesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/ai': typeof AppAiRoute
  '/chat': typeof AppChatRoute
  '/circles': typeof AppCirclesRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/circles/$id': typeof AppCirclesIdRoute
  '/profile/$userId': typeof AppProfileUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/ai': typeof AppAiRoute
  '/chat': typeof AppChatRoute
  '/circles': typeof AppCirclesRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/circles/$id': typeof AppCirclesIdRoute
  '/profile/$userId': typeof AppProfileUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/circles': typeof AppCirclesRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/marketplace': typeof AppMarketplaceRoute
  '/_app/circles/$id': typeof AppCirclesIdRoute
  '/_app/profile/$userId': typeof AppProfileUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot'
    | '/login'
    | '/signup'
    | '/ai'
    | '/chat'
    | '/circles'
    | '/dashboard'
    | '/marketplace'
    | '/circles/$id'
    | '/profile/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/forgot'
    | '/login'
    | '/signup'
    | '/ai'
    | '/chat'
    | '/circles'
    | '/dashboard'
    | '/marketplace'
    | '/circles/$id'
    | '/profile/$userId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/forgot'
    | '/login'
    | '/signup'
    | '/_app/ai'
    | '/_app/chat'
    | '/_app/circles'
    | '/_app/dashboard'
    | '/_app/marketplace'
    | '/_app/circles/$id'
    | '/_app/profile/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRoute
  ForgotRoute: typeof ForgotRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/marketplace': {
      id: '/_app/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/circles': {
      id: '/_app/circles'
      path: '/circles'
      fullPath: '/circles'
      preLoaderRoute: typeof AppCirclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/$userId': {
      id: '/_app/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AppProfileUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/circles/$id': {
      id: '/_app/circles/$id'
      path: '/$id'
      fullPath: '/circles/$id'
      preLoaderRoute: typeof AppCirclesIdRouteImport
      parentRoute: typeof AppCirclesRoute
    }
  }
}

interface AppCirclesRouteChildren {
  AppCirclesIdRoute: typeof AppCirclesIdRoute
}

const AppCirclesRouteChildren: AppCirclesRouteChildren = {
  AppCirclesIdRoute: AppCirclesIdRoute,
}

const AppCirclesRouteWithChildren = AppCirclesRoute._addFileChildren(
  AppCirclesRouteChildren,
)

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppChatRoute: typeof AppChatRoute
  AppCirclesRoute: typeof AppCirclesRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppProfileUserIdRoute: typeof AppProfileUserIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppChatRoute: AppChatRoute,
  AppCirclesRoute: AppCirclesRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppProfileUserIdRoute: AppProfileUserIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRoute,
  ForgotRoute: ForgotRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
